/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface AccountsService {

    /**
    * Retrieve a single user
    * Returns public info about a single user
    * @param id ID of the user 
    * @return Single<UserResponse>
    */
	@GET("accounts/{id}")
    fun getAccount(@Path("id") id: String): Single<UserResponse>
}
