/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface AlertsService {

    /**
    * Create an alert
    * 
    * @param payload Alert settings (optional)
    * @return Single<AlertResponse>
    */
	@POST("alerts")
    fun createAlert(@Body payload: AlertSettings? = null): Single<AlertResponse>
    /**
    * Delete an alert
    * 
    * @param id Id of the alert to be deleted 
    * @return void
    */
	@DELETE("alerts/{id}")
    fun deleteAlert(@Path("id") id: String): Single<EmptyResponse>
    /**
    * Retrieve an alert
    * 
    * @param id Id of the alert to be retrieved 
    * @return Single<AlertResponse>
    */
	@GET("alerts/{id}")
    fun getAlert(@Path("id") id: String): Single<AlertResponse>
    /**
    * Average number of new products
    * Returns the average number of newly available products per day/week/month that match given criteria. 
    * @param path Path (eg. &#x60;/woman/woman-bags&#x60;) (optional)
    * @param searchQuery Search query (eg. &#x60;leather+boots&#x60;) (optional)
    * @param idUniverse Universe Id (optional)
    * @param idBrand Brand Ids (optional)
    * @param idMaterials Material Ids (optional)
    * @param idPattern Pattern Ids (optional)
    * @param idColors Color Ids (optional)
    * @param idCondition Condition Ids (optional)
    * @param idCategory Category Ids (optional)
    * @param idSubcategory Subcategory Ids (optional)
    * @param idSize Size Ids (optional)
    * @param stock In stock (optional)
    * @return Single<AverageProductsResponse>
    */
	@GET("alerts/average-matching-products")
    fun getProductsAverageMatching(@Query("path") path: String? = null, @Query("searchQuery") searchQuery: String? = null, @Query("idUniverse") idUniverse: String? = null, @Query("idBrand") idBrand: Array<String>? = null, @Query("idMaterials") idMaterials: Array<String>? = null, @Query("idPattern") idPattern: Array<String>? = null, @Query("idColors") idColors: Array<String>? = null, @Query("idCondition") idCondition: Array<String>? = null, @Query("idCategory") idCategory: Array<String>? = null, @Query("idSubcategory") idSubcategory: Array<String>? = null, @Query("idSize") idSize: Array<String>? = null, @Query("stock") stock: String? = null): Single<AverageProductsResponse>
    /**
    * List alerts
    * Lists alerts of current user
    * @param limit This is the maximum number of objects that may be returned. (optional, default to 10)
    * @param offset This offsets the start of each page by the number specified. (optional, default to 0)
    * @return Single<AlertListResponse>
    */
	@GET("alerts")
    fun listAlerts(@Query("limit") limit: Int? = null, @Query("offset") offset: Int? = null): Single<AlertListResponse>
}
