/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface BrandsService {

    /**
    * Dislike a brand
    * 
    * @param id Id of the brand to dislike 
    * @return void
    */
	@DELETE("brands/{id}/likes")
    fun dislikeBrand(@Path("id") id: String): Single<EmptyResponse>
    /**
    * List brands
    * Returns all brands
    * @param active get only active brands (optional, default to false)
    * @return Single<BrandListResponse>
    */
	@GET("brands")
    fun listBrands(@Query("active") active: Boolean? = null): Single<BrandListResponse>
}
