/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface BreadcrumbsService {

    /**
    * Get breadcrumb
    * Return a breadcrumb: an ordered list of url+label to be displayed on the url that is queried (in french: Fil d&#39;ariane)
    * @param url Url which we want the breadcrumb 
    * @return Single<BreadcrumbResponse>
    */
	@GET("breadcrumbs")
    fun getBreadcrumb(@Query("url") url: String): Single<BreadcrumbResponse>
}
