/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface CampaignsService {

    /**
    * Get a campaign by id
    * 
    * @param id Campaign ID to query 
    * @return Single<CampaignResponse>
    */
	@GET("campaigns/{id}")
    fun getCampaign(@Path("id") id: String): Single<CampaignResponse>
}
