/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface CommentsService {

    /**
    * Like a comment
    * Add a Like on a comment
    * @param id Comment id 
    * @return void
    */
	@POST("comments/{id}/likes")
    fun likeComment(@Path("id") id: String): Single<EmptyResponse>
    /**
    * Unlike a comment
    * Delete a Like from a comment
    * @param id Comment id 
    * @return void
    */
	@DELETE("comments/{id}/likes")
    fun unlikeComment(@Path("id") id: String): Single<EmptyResponse>
}
