/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface NewsletterSubscribersService {

    /**
    * Register an email to the newsletter
    * 
    * @param payload Newsletter registration (optional)
    * @return Single<NewsletterRegistrationResponse>
    */
	@POST("newsletter-subscribers")
    fun subscribeNewsletter(@Body payload: NewsletterRegistration? = null): Single<NewsletterRegistrationResponse>
}
