/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface NotificationsService {

    /**
    * Returns a list of notifications
    * 
    * @param limit This is the maximum number of objects that may be returned. (optional, default to 10)
    * @param offset This offsets the start of each page by the number specified. (optional, default to 0)
    * @return Single<NotificationListResponse>
    */
	@GET("notifications")
    fun listNotifications(@Query("limit") limit: Int? = null, @Query("offset") offset: Int? = null): Single<NotificationListResponse>
    /**
    * Mark notification Id as viewed or read (default read)
    * 
    * @param id Notification Id to mark as viewed or read 
    * @param payload  (optional)
    * @return Single<EmptyResponse>
    */
	@PATCH("notifications/{id}")
    fun updateNotification(@Path("id") id: String, @Body payload: NotificationUpdateRequest? = null): Single<EmptyResponse>
    /**
    * Notifications Ids to mark as viewed
    * 
    * @param payload  
    * @return Single<EmptyResponse>
    */
	@PATCH("notifications")
    fun updateNotifications(@Body payload: ViewedNotificationIds): Single<EmptyResponse>
}
