/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface PaymentMethodsService {

    /**
    * return a specific payment method
    * 
    * @param id The id of a paymentMethod 
    * @return Single<PaymentMethodResponse>
    */
	@GET("payment-methods/{id}")
    fun getPaymentMethod(@Path("id") id: String): Single<PaymentMethodResponse>
    /**
    * List payment methods
    * Returns all allowed payment method for UserMe
    * @param limit This is the maximum number of objects that may be returned. (optional, default to 10)
    * @param offset This offsets the start of each page by the number specified. (optional, default to 0)
    * @return Single<PaymentMethodListResponse>
    */
	@GET("payment-methods")
    fun listPaymentMethods(@Query("limit") limit: Int? = null, @Query("offset") offset: Int? = null): Single<PaymentMethodListResponse>
}
