/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface PricesService {

    /**
    * pvn estimated
    * return the pvn (seller&#39;s share)
    * @param price  
    * @param currency defaults to user&#39;s currency (i18n) (optional)
    * @param idProduct  (optional)
    * @param idClient  (optional)
    * @return Single<PriceResponse>
    */
	@GET("prices")
    fun getPrice(@Query("price") price: String, @Query("currency") currency: String? = null, @Query("idProduct") idProduct: String? = null, @Query("idClient") idClient: String? = null): Single<PriceResponse>
}
