/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface SessionsService {

    /**
    * Log-in (create a new session)
    * 
    * @param payload  (optional)
    * @return Single<SessionResponse>
    */
	@POST("sessions")
    fun createSession(@Body payload: Credentials? = null): Single<SessionResponse>
    /**
    * Delete an user session (log-out)
    * 
    * @param sessionId Session id 
    * @return void
    */
	@DELETE("sessions/{sessionId}")
    fun deleteSession(@Path("sessionId") sessionId: String): Single<EmptyResponse>
}
