/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface ShippingPlanService {

    /**
    * Shipping Eligibility
    * Returns a Shipping Eligibility for a country
    * @param country ISO Country Code 
    * @return Single<ShippingPlanResponse>
    */
	@GET("shipping-plan/eligibility")
    fun getShippingEligibility(@Query("country") country: String): Single<ShippingPlanResponse>
}
