/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.api

import fr.vestiairecollective.network.redesign.model.*
import io.reactivex.Single
import retrofit2.http.*

interface ShippingMethodsService {

    /**
    * Retrieve a shipping method
    * Returns information about a specific shipping method.
    * @param id The Id of a shipping method 
    * @return Single<ShippingMethodResponse>
    */
	@GET("shipping-methods/{id}")
    fun getShippingMethod(@Path("id") id: String): Single<ShippingMethodResponse>
    /**
    * List shipping methods
    * Returns available shipping methods for current order.
    * @param limit This is the maximum number of objects that may be returned. (optional, default to 10)
    * @param offset This offsets the start of each page by the number specified. (optional, default to 0)
    * @return Single<ShippingMethodListResponse>
    */
	@GET("shipping-methods")
    fun listShippingMethods(@Query("limit") limit: Int? = null, @Query("offset") offset: Int? = null): Single<ShippingMethodListResponse>
}
