/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class AccountCivility() {

    /* User civility name */
    lateinit var name: AccountCivility.Name
    /* User civility name (localized) */
    lateinit var localizedName: String

    constructor(name: Name, localizedName: String) : this() {
        this.name = name
        this.localizedName = localizedName
    }


    enum class Name(val value: String) {
    
        mr("mr"),
    
        mrs("mrs"),
    
        miss("miss"),
    
        mme("mme"),
    
        mlle("mlle"),
    
        sr.("sr."),
    
        sra.("sra."),
    
        srta.("srta."),
    
        sig.("sig."),
    
        sig.ra("sig.ra"),
    
        sig.na("sig.na"),
    
        herr("herr"),
    
        frau("frau"),
    
        fräulein("fräulein");
    
    }

}

