/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Account() {

    lateinit var id: String
    lateinit var type: Account.Type
    /* user firstname */
    lateinit var firstname: String
    lateinit var civility: AccountCivility
    /* User name */
    var username: String? = null
    /* user email */
    var email: String? = null
    var statistics: AccountStatistics? = null
    var badges: Array<AccountBadge>? = null

    constructor(id: String, type: Type, firstname: String, civility: AccountCivility) : this() {
        this.id = id
        this.type = type
        this.firstname = firstname
        this.civility = civility
    }


    enum class Type(val value: String) {
    
        account("account");
    
    }

}

