/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class AccountStatistics() {
    /* number of products that have been sold */
    var productsSold: Int = 0
    /* number of products that have been buy */
    var productsBuyed: Int = 0
    /* number of products that have been listed */
    var productsListed: Int = 0
    /* number of products that have been added in wishlist */
    var productsWished: Int = 0

    /* x% of this seller's items have passed quality control, transform_rate in legacy */
    var passRate: Double? = null

    constructor(productsSold: Int, productsBuyed: Int, productsListed: Int, productsWished: Int) : this() {
        this.productsSold = productsSold
        this.productsBuyed = productsBuyed
        this.productsListed = productsListed
        this.productsWished = productsWished
    }


}

