/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

/**
* Describe user public status
* Values: pro,recommended,premium,depositor,direct-shipping
*/
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
enum class AccountBadge(val value: String){

    pro("pro"),

    recommended("recommended"),

    premium("premium"),

    depositor("depositor"),

    direct-shipping("direct-shipping");

}

