/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Address() {

    lateinit var id: String
    lateinit var type: Address.Type
    /* First and main part of the adress */
    lateinit var address1: String
    /* Zip code */
    lateinit var zipCode: String
    lateinit var city: String
    /* Additionnal information about the adress */
    var address2: String? = null
    var states: String? = null
    /* [Relationship] Address country */
    var country: Country? = null

    constructor(id: String, type: Type, address1: String, zipCode: String, city: String) : this() {
        this.id = id
        this.type = type
        this.address1 = address1
        this.zipCode = zipCode
        this.city = city
    }


    enum class Type(val value: String) {
    
        address("address");
    
    }

}

