/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class AlertCriterion() {

    /* Criterion identifier */
    lateinit var key: AlertCriterionKey
    /* Criterion value */
    lateinit var value: Array<String>

    constructor(key: AlertCriterionKey, value: Array<String>) : this() {
        this.key = key
        this.value = value
    }


}

