/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

/**
* 
* Values: path,searchQuery,idUniverse,idBrand,idMaterials,idPattern,idColors,idSeason,idCondition,idCategory,idSubcategory,idSize,idProduct,idModel,idWatchMechanism,discount,tags,priceMin,priceMax,stock
*/
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
enum class AlertCriterionKey(val value: String){

    path("path"),

    searchQuery("searchQuery"),

    idUniverse("idUniverse"),

    idBrand("idBrand"),

    idMaterials("idMaterials"),

    idPattern("idPattern"),

    idColors("idColors"),

    idSeason("idSeason"),

    idCondition("idCondition"),

    idCategory("idCategory"),

    idSubcategory("idSubcategory"),

    idSize("idSize"),

    idProduct("idProduct"),

    idModel("idModel"),

    idWatchMechanism("idWatchMechanism"),

    discount("discount"),

    tags("tags"),

    priceMin("priceMin"),

    priceMax("priceMax"),

    stock("stock");

}

