/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class AlertSettings() {

    /* Alert category */
    lateinit var category: AlertCategory
    /* A list of alert criteria */
    lateinit var criteria: Array<AlertCriterion>
    /* A list of notification channels */
    var channels: Array<NotificationChannel>? = null
    /* Notification frequency */
    var frequency: NotificationFrequency? = null

    constructor(category: AlertCategory, criteria: Array<AlertCriterion>) : this() {
        this.category = category
        this.criteria = criteria
    }


}

