/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

/**
* 
* Values: newProduct,priceDrop,memberNewProduct,memberPriceDrop,memberWishlist,memberLike
*/
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
enum class AlertCategory(val value: String){

    newProduct("newProduct"),

    priceDrop("priceDrop"),

    memberNewProduct("memberNewProduct"),

    memberPriceDrop("memberPriceDrop"),

    memberWishlist("memberWishlist"),

    memberLike("memberLike");

}

