/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Alert() {

    lateinit var id: String
    lateinit var type: Alert.Type
    /* Alert category */
    lateinit var category: AlertCategory
    /* Notification channels */
    lateinit var channels: Array<NotificationChannel>
    /* Notification frequency */
    lateinit var frequency: NotificationFrequency
    /* List of criteria triggering the alert */
    lateinit var criteria: Array<AlertCriterion>
    /* A human-readable name */
    var name: String? = null
    /* A human-readable name (localized) */
    var localizedName: String? = null
    /* Date when alert was created */
    var creationDate: java.util.Calendar? = null

    constructor(id: String, type: Type, category: AlertCategory, channels: Array<NotificationChannel>, frequency: NotificationFrequency, criteria: Array<AlertCriterion>) : this() {
        this.id = id
        this.type = type
        this.category = category
        this.channels = channels
        this.frequency = frequency
        this.criteria = criteria
    }


    enum class Type(val value: String) {
    
        alert("alert");
    
    }

}

