/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class BuyerFee() {

    lateinit var rateType: RateType    /* buyer fee rate/value */
    var value: Float = 0.0f

    lateinit var cost: Price
    /* Buyer fee description */
    var description: String? = null

    constructor(rateType: RateType, value: Float, cost: Price) : this() {
        this.rateType = rateType
        this.value = value
        this.cost = cost
    }


}

