/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Campaign() {

    lateinit var id: String
    lateinit var type: Campaign.Type
    /* campaign title */
    lateinit var title: String
    /* campaign description */
    lateinit var description: String
    /* the banner to show on the page */
    lateinit var banner: String
    /* localized campaign title */
    var localizedTitle: String? = null
    /* localized campaign description */
    var localizedDescription: String? = null

    constructor(id: String, type: Type, title: String, description: String, banner: String) : this() {
        this.id = id
        this.type = type
        this.title = title
        this.description = description
        this.banner = banner
    }


    enum class Type(val value: String) {
    
        campaign("campaign");
    
    }

}

