/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class CatalogFacetLink {
    /* Universe facet link */
    var universes: Array<CatalogFacet>? = null
    /* Categories facet link */
    var categories: Array<CatalogFacet>? = null
    /* SubCategories facet link */
    var subCategories: Array<CatalogFacet>? = null
    /* SubSubCategories facet link */
    var subSubCategories: Array<CatalogFacet>? = null
    /* Brand facet link */
    var brand: Array<CatalogFacet>? = null
    /* Model facet link */
    var model: Array<CatalogFacet>? = null
    /* Color facet link */
    var color: Array<CatalogFacet>? = null
    /* Material facet link */
    var material: Array<CatalogFacet>? = null
    /* Vintage facet link */
    var editorPicks: Array<CatalogFacet>? = null



}

