/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class CatalogPage() {

    lateinit var id: String
    lateinit var type: CatalogPage.Type
    /* Path */
    lateinit var path: String
    /* Language code */
    lateinit var language: String
    /* Page template */
    lateinit var template: String
    lateinit var metadata: ContentsPageMetadata
    lateinit var indexation: ContentsPageIndexation
    /* Route details */
    lateinit var route: ContentsRoute
    lateinit var content: ContentsCatalogPageContent    /* true if pagination is opened */
    var isOpenedForPagination: Boolean = false

    /* Regional variations of the page. */
    var alternateVersions: Array<ContentsLocalizedPath>? = null

    constructor(id: String, type: Type, path: String, language: String, template: String, metadata: ContentsPageMetadata, indexation: ContentsPageIndexation, route: ContentsRoute, content: ContentsCatalogPageContent, isOpenedForPagination: Boolean) : this() {
        this.id = id
        this.type = type
        this.path = path
        this.language = language
        this.template = template
        this.metadata = metadata
        this.indexation = indexation
        this.route = route
        this.content = content
        this.isOpenedForPagination = isOpenedForPagination
    }


    enum class Type(val value: String) {
    
        catalog-page("catalog-page");
    
    }

}

