/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Comment() {

    lateinit var id: String
    lateinit var type: Comment.Type
    lateinit var message: String
    var isNegotiationSellerOffer: Boolean? = null
    var isTranslatable: Boolean? = null
    var nbLike: Int? = null
    var date: java.util.Calendar? = null
    /* [Relationship] */
    var product: Product? = null
    /* [Relationship] */
    var author: User? = null

    constructor(id: String, type: Type, message: String) : this() {
        this.id = id
        this.type = type
        this.message = message
    }


    enum class Type(val value: String) {
    
        comment("comment");
    
    }

}

