/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Commission() {

    /* seller's share */
    lateinit var pvnPrice: Price
    /* price */
    lateinit var price: Price

    constructor(pvnPrice: Price, price: Price) : this() {
        this.pvnPrice = pvnPrice
        this.price = price
    }


}

