/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsBlockContentDetail {
    /* block target */
    var target: String? = null
    /* block title */
    var title: String? = null
    /* block top title */
    var supTitle: String? = null
    /* block bottom title */
    var subTitle: String? = null
    /* color in hex */
    var backgroundColor: String? = null
    var images: Array<String>? = null
    /* absolute url for call to action */
    var cta: String? = null
    /* absolute url for block link */
    var link: String? = null
    /* text field for blocks (in html) */
    var textarea: String? = null



}

