/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsRouteParameter() {

    /* Parameter name */
    lateinit var name: ContentsRouteParameter.Name
    /* Parameter value */
    lateinit var value: String

    constructor(name: Name, value: String) : this() {
        this.name = name
        this.value = value
    }


    enum class Name(val value: String) {
    
        idUniverse("idUniverse"),
    
        idBrand("idBrand"),
    
        idColors("idColors"),
    
        idMaterials("idMaterials"),
    
        idCategory("idCategory"),
    
        idSubcategory("idSubcategory"),
    
        idSubSubcategory("idSubSubcategory"),
    
        idProduct("idProduct"),
    
        idModel("idModel"),
    
        tag("tag"),
    
        stock("stock");
    
    }

}

