/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsPageIndexation() {
    /* Allow search engines to add the page to their index. */
    var index: Boolean = false
    /* Tells the search engines that it may follow links on the page. */
    var follow: Boolean = false
    /* Tells us if we can let Search Engine to do pagination crawling */
    var crawlPagination: Boolean = false


    constructor(index: Boolean, follow: Boolean, crawlPagination: Boolean) : this() {
        this.index = index
        this.follow = follow
        this.crawlPagination = crawlPagination
    }


}

