/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsBlock {
    /* The text to be displayed in the link */
    var text: String? = null
    /* The second line of text to be displayed in the link */
    var cta: String? = null
    /* Hexadecimal color code for the link's background */
    var color: String? = null
    var url: Url? = null
    /* position of the button */
    var buttonPosition: ContentsBlock.ButtonPosition? = null
    var picture: Picture? = null
    var mobilePicture: Picture? = null



    enum class ButtonPosition(val value: String) {
    
        top-left("top-left"),
    
        bottom-left("bottom-left"),
    
        top-right("top-right"),
    
        bottom-right("bottom-right"),
    
        center("center");
    
    }

}

