/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsSingleEdito {
    /* BO name */
    var name: String? = null
    /* Title to be displayed into the content */
    var title: String? = null
    /* Text to be displayed into the content */
    var text: String? = null
    /* Text to be displayed in italic into the content */
    var italicText: String? = null
    var url: Url? = null
    /* Hexadecimal color for the background */
    var backgroundColor: String? = null
    /* Hexadecimal color for the text */
    var textColor: String? = null
    var pictures: Array<Picture>? = null



}

