/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsPromotionalBanner() {

    /* Text to be displayed in the banner */
    lateinit var content: String
    /* Text to be displayed in the footer */
    lateinit var contentLegals: String
    /* Link / Deeplink (for mobile applications) to the landing page */
    lateinit var link: String
    /* Short text to be displayed in the banner (mobile) */
    var contentShort: String? = null
    /* Hexadecimal color code for background */
    var backgroundColor: String? = null
    /* Hexadecimal color code for text */
    var textColor: String? = null

    constructor(content: String, contentLegals: String, link: String) : this() {
        this.content = content
        this.contentLegals = contentLegals
        this.link = link
    }


}

