/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsCategories() {

    /* Name for backend purposes */
    lateinit var name: String
    lateinit var blocks: Array<ContentsCategoriesBlock>

    constructor(name: String, blocks: Array<ContentsCategoriesBlock>) : this() {
        this.name = name
        this.blocks = blocks
    }


}

