/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsCustomerCare() {

    /* Phone number */
    lateinit var phone: String
    /* Opening times */
    lateinit var schedule: String
    /* Phone number premium */
    var phonePremium: String? = null
    /* Phone number premium */
    var schedulePremium: String? = null

    constructor(phone: String, schedule: String) : this() {
        this.phone = phone
        this.schedule = schedule
    }


}

