/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsBlockContent {
    /* blockId */
    var id: String? = null
    var tags: Array<String>? = null
    var createdAt: java.util.Calendar? = null
    var updatedAt: java.util.Calendar? = null
    var label: String? = null
    var blocks: Array<ContentsLanguageBlock>? = null



}

