/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ContentsCatalogPageContent() {

    /* Page headline */
    lateinit var headline: String
    /* Featured categories */
    var carousel: Array<ContentsCarouselItem>? = null
    /* Introduction text */
    var intro: String? = null
    /* Body of the page */
    var body: String? = null

    constructor(headline: String) : this() {
        this.headline = headline
    }


}

