/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Credentials {
    /* user's email */
    var email: String? = null
    /* user's password */
    var password: String? = null
    /* Social user ID */
    var socialId: String? = null
    /* Social user account type */
    var socialAccountType: Credentials.SocialAccountType? = null
    /* Social user token */
    var socialToken: String? = null



    enum class SocialAccountType(val value: String) {
    
        facebook("facebook");
    
    }

}

