/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

/**
* 
* Values: EUR,USD,GBP,SGD,SEK,HKD,CAD,AUD,CHF,PLN,DKK
*/
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
enum class Currency(val value: String){

    EUR("EUR"),

    USD("USD"),

    GBP("GBP"),

    SGD("SGD"),

    SEK("SEK"),

    HKD("HKD"),

    CAD("CAD"),

    AUD("AUD"),

    CHF("CHF"),

    PLN("PLN"),

    DKK("DKK");

}

