/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class DeliveryTime() {

    lateinit var id: String
    lateinit var type: DeliveryTime.Type    /* Estimated delivery delay */
    var sendDelay: Int = 0


    constructor(id: String, type: Type, sendDelay: Int) : this() {
        this.id = id
        this.type = type
        this.sendDelay = sendDelay
    }


    enum class Type(val value: String) {
    
        deliveryTime("deliveryTime");
    
    }

}

