/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ErrorResponse() {

    lateinit var errors: ErrorDetail
    /* An object containing meta-information about the error */
    lateinit var meta: Empty

    constructor(errors: ErrorDetail, meta: Empty) : this() {
        this.errors = errors
        this.meta = meta
    }


}

