/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class HeaderBadgeDetail() {
    /* Count orderline to display on header */
    var orderLineCount: Int = 0
    /* Count active notification to display on header */
    var notificationCount: Int = 0
    /* Count wishList product to display on header */
    var wishListCount: Int = 0


    constructor(orderLineCount: Int, notificationCount: Int, wishListCount: Int) : this() {
        this.orderLineCount = orderLineCount
        this.notificationCount = notificationCount
        this.wishListCount = wishListCount
    }


}

