/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class I18n() {

    /* I18n's country */
    lateinit var country: String
    /* I18n's language */
    lateinit var language: String
    /* I18n's currency */
    lateinit var currency: String
    /* I18n's siteId */
    var siteId: String? = null

    constructor(country: String, language: String, currency: String) : this() {
        this.country = country
        this.language = language
        this.currency = currency
    }


}

