/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Language() {

    /* Original language name */
    lateinit var name: String
    /* Language name (localized) */
    lateinit var localizedName: String
    /* Language code ISO 639-1 */
    lateinit var code: String

    constructor(name: String, localizedName: String, code: String) : this() {
        this.name = name
        this.localizedName = localizedName
        this.code = code
    }


}

