/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Model() {

    lateinit var id: String
    lateinit var type: Model.Type
    /* Model name */
    var name: String? = null
    /* Model name (localized) */
    var localizedName: String? = null

    constructor(id: String, type: Type) : this() {
        this.id = id
        this.type = type
    }


    enum class Type(val value: String) {
    
        model("model");
    
    }

}

