/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class NegotiationEventRequest() {

    /* Type of action ('accept', 'reject' or 'offer') */
    lateinit var action: NegotiationEventRequest.Action
    /* Offer price in current currency, without cents (127 for 127€) */
    var offerInWholeNumber: AmountInWholeNumber? = null

    constructor(action: Action) : this() {
        this.action = action
    }


    enum class Action(val value: String) {
    
        accept("accept"),
    
        reject("reject"),
    
        offer("offer");
    
    }

}

