/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class NegotiationRequest() {

    /* Offer price in current currency, without cents (127 for 127€) */
    lateinit var offerInWholeNumber: AmountInWholeNumber
    /* Buyer account id, only if negotiation is initiated by seller */
    var buyerId: String? = null

    constructor(offerInWholeNumber: AmountInWholeNumber) : this() {
        this.offerInWholeNumber = offerInWholeNumber
    }


}

