/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class NegotiationEvent() {

    lateinit var id: String
    lateinit var type: NegotiationEvent.Type
    /* Type of event. Can be one of the following:   - offer: offer or counter-offer   - accept: acceptation of an offer   - reject: rejection of an offer, without making a counter-offer   - order: action of buying the product (after payment and anti-fraud controls)   - external: external actions that directly impact the negotiation (for example: ! product bought by someone else)  */
    lateinit var action: NegotiationEvent.Action
    /* Date when event was created */
    lateinit var creationDate: java.util.Calendar
    /* Role of the user who created the event */
    lateinit var createdBy: NegotiationEvent.CreatedBy
    /* Displayable translated message that describes the status of the negotiation */
    lateinit var userMessage: String
    /* Current offer price */
    lateinit var price: Price
    /* PVN (Seller share). Only if the caller if the seller */
    var sellerPvnPrice: Price? = null

    constructor(id: String, type: Type, action: Action, creationDate: java.util.Calendar, createdBy: CreatedBy, userMessage: String, price: Price) : this() {
        this.id = id
        this.type = type
        this.action = action
        this.creationDate = creationDate
        this.createdBy = createdBy
        this.userMessage = userMessage
        this.price = price
    }


    enum class Type(val value: String) {
    
        negotiationEvent("negotiationEvent");
    
    }

    enum class Action(val value: String) {
    
        offer("offer"),
    
        accept("accept"),
    
        reject("reject"),
    
        order("order"),
    
        `external`("external");
    
    }

    enum class CreatedBy(val value: String) {
    
        seller("seller"),
    
        buyer("buyer"),
    
        vc("vc");
    
    }

}

