/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class OrderLine() {

    lateinit var id: String
    lateinit var type: OrderLine.Type
    /* [Relationship] Order line's product */
    lateinit var product: Product
    /* Date of creation of the order line */
    var creationDate: java.util.Calendar? = null
    var duties: Duty? = null
    var buyerFees: Array<BuyerFee>? = null
    var plans: Array<PlanOption>? = null

    constructor(id: String, type: Type, product: Product) : this() {
        this.id = id
        this.type = type
        this.product = product
    }


    enum class Type(val value: String) {
    
        orderLine("orderLine");
    
    }

}

