/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class PaymentMethod() {

    /* name of the payment method */
    lateinit var name: String
    /* mnemonic of the payment method */
    lateinit var mnemonic: String
    var icon: Picture? = null
    /* payment method information */
    var disclaimer: String? = null

    constructor(name: String, mnemonic: String) : this() {
        this.name = name
        this.mnemonic = mnemonic
    }


}

