/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Picture() {

    /* Picture path */
    lateinit var path: String
    var url: Url? = null
    /* Image width */
    var width: Int? = null
    /* Image height */
    var height: Int? = null
    /* Image center y */
    var centery: Float? = null
    /* Picture name */
    var name: String? = null
    /* Alternative name if not exist (seo needed) */
    var alt: String? = null

    constructor(path: String) : this() {
        this.path = path
    }


}

