/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class PlanOption() {

    /* Plan code (identifier) */
    lateinit var code: String
    /* Plan name */
    lateinit var name: String
    /* Plan's services */
    lateinit var services: Array<PlanService>
    /* Selected plan */
    var selected: Boolean? = null

    constructor(code: String, name: String, services: Array<PlanService>) : this() {
        this.code = code
        this.name = name
        this.services = services
    }


}

