/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class PlanService() {

    /* Service code (identifier) */
    lateinit var code: String
    /* Service name */
    var name: String? = null
    /* Is service availlable in plan */
    var available: Boolean? = null
    var cost: Price? = null

    constructor(code: String) : this() {
        this.code = code
    }


}

