/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Price() {

    lateinit var currency: Currency    /* amount in cents */
    var cents: Int = 0

    /* formatted amount with currency */
    lateinit var formatted: String

    constructor(currency: Currency, cents: Int, formatted: String) : this() {
        this.currency = currency
        this.cents = cents
        this.formatted = formatted
    }


}

