/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ProductMeshLinks {
    /* top category seo informations */
    var topCategory: Empty? = null
    /* category seo informations */
    var category: Empty? = null
    /* category / brand seo informations */
    var categoryBrand: Empty? = null
    /* category / brand / model seo information */
    var categoryBrandModel: Empty? = null
    /* category / brand / model / material seo information */
    var categoryBrandModelMaterial: Empty? = null
    /* category / brand / model / material / color seo information */
    var categoryBrandModelMaterialColor: Empty? = null



}

