/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ProductPackaging() {

    /* Packaging name (localized) */
    lateinit var localizedName: String    /* Product has this packaging or not */
    var value: Boolean = false

    /* Packaging name */
    var name: String? = null

    constructor(localizedName: String, value: Boolean) : this() {
        this.localizedName = localizedName
        this.value = value
    }


}

