/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class ProductConditionLevel {
    /* Name of condition level */
    var name: String? = null
    /* Explanatory text to determinate and know reasons why a product is considered to be in a good condition */
    var good: String? = null
    /* Explanatory text to determinate and know reasons why a product is considered to be in a bad condition */
    var bad: String? = null



}

