/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Session() {

    lateinit var id: String
    lateinit var type: Session.Type
    lateinit var i18n: I18n
    /* [Relationship] */
    var user: User? = null

    constructor(id: String, type: Type, i18n: I18n) : this() {
        this.id = id
        this.type = type
        this.i18n = i18n
    }


    enum class Type(val value: String) {
    
        session("session");
    
    }

}

