/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Shipping {
    var warehouse: Warehouse? = null
    var destinationCountry: Country? = null
    var cost: ShippingCost? = null
    /* Product will be shipped within X business days */
    var sendDelay: Int? = null
    /* Product will be shipped on {sendDay} */
    var sendDay: String? = null
    /* The product is prohibited in user's country */
    var prohibited: Boolean? = null
    /* Product can be shipped to user's country */
    var buyable: Boolean? = null



}

