/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Size() {

    lateinit var id: String
    lateinit var type: Size.Type
    /* size */
    lateinit var size: String
    var standard: String? = null
    var localizedStandard: String? = null

    constructor(id: String, type: Type, size: String) : this() {
        this.id = id
        this.type = type
        this.size = size
    }


    enum class Type(val value: String) {
    
        size("size");
    
    }

}

