/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Url() {

    /* Url path */
    lateinit var path: String
    /* full url, with localized hostname */
    lateinit var url: String
    /* Original url */
    var original: String? = null
    /* Mobile dedicated url */
    var mobile: String? = null

    constructor(path: String, url: String) : this() {
        this.path = path
        this.url = url
    }


}

