/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class UserSocial() {
    /* number of people followed by the user */
    var nbFollows: Int = 0
    /* number of people following the user */
    var nbFollowers: Int = 0
    /* number of products that have been liked */
    var productsLiked: Int = 0
    /* Community rank based on social interaction on the website */
    var communityRank: Int = 0

    /* Status of a user to know if the user is followed or not */
    var followed: Boolean? = null

    constructor(nbFollows: Int, nbFollowers: Int, productsLiked: Int, communityRank: Int) : this() {
        this.nbFollows = nbFollows
        this.nbFollowers = nbFollowers
        this.productsLiked = productsLiked
        this.communityRank = communityRank
    }


}

