/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class UserGoalThreshold() {

    /* The type of goal threshold */
    lateinit var category: UserGoalThreshold.Category    /* The max value (a rate or an integer) */
    var maxValue: Double

    lateinit var thresholds: Array<UserThreshold>

    constructor(category: Category, maxValue: Double, thresholds: Array<UserThreshold>) : this() {
        this.category = category
        this.maxValue = maxValue
        this.thresholds = thresholds
    }


    enum class Category(val value: String) {
    
        conformity("conformity"),
    
        shipping("shipping"),
    
        volume("volume");
    
    }

}

