/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class UserSellerRatingGoals() {
    /* The sold product acceptance rate (quality and authentication) */
    var conformity: Float = 0.0f
    /* The customer experience (comment answering time) */
    var cx: Float = 0.0f
    /* Cancellation rate */
    var shipping: Float = 0.0f
    /* The number of products sold in the last three months */
    var volume: Int = 0

    var tags: UserSellerRatingGoalsTags? = null

    constructor(conformity: Float, cx: Float, shipping: Float, volume: Int) : this() {
        this.conformity = conformity
        this.cx = cx
        this.shipping = shipping
        this.volume = volume
    }


}

