/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class UserApp() {

    /* Application name */
    lateinit var key: UserApp.Key
    /* Application ID value */
    lateinit var value: String

    constructor(key: Key, value: String) : this() {
        this.key = key
        this.value = value
    }


    enum class Key(val value: String) {
    
        android("android"),
    
        ios("ios");
    
    }

}

