/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class UserOwnCounters() {
    /* User's number of product on sale */
    var productOnSale: Int = 0
    /* User's number of product in progress (waiting photo) */
    var productWaitingPicture: Int = 0
    /* Users's number of product in progress (waiting validation) */
    var productWaitingValidation: Int = 0
    /* User's number of product sold */
    var productSold: Int = 0
    /* User's number of product refused */
    var productRefused: Int = 0
    /* User's number of product unreceived */
    var productUnreceived: Int = 0


    constructor(productOnSale: Int, productWaitingPicture: Int, productWaitingValidation: Int, productSold: Int, productRefused: Int, productUnreceived: Int) : this() {
        this.productOnSale = productOnSale
        this.productWaitingPicture = productWaitingPicture
        this.productWaitingValidation = productWaitingValidation
        this.productSold = productSold
        this.productRefused = productRefused
        this.productUnreceived = productUnreceived
    }


}

