/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class User() {

    lateinit var id: String
    lateinit var type: User.Type
    /* user firstname */
    lateinit var firstname: String
    lateinit var civility: UserCivility
    lateinit var language: Language
    /* User name */
    var username: String? = null
    /* user email */
    var email: String? = null
    /* a flag which shows if a client has a has a wallet */
    var hasWallet: Boolean? = null
    var picture: Picture? = null
    var cover: Picture? = null
    var url: Url? = null
    /* Birth date (AAAA-MM-DDT00:00:00Z) */
    var birthDate: java.util.Calendar? = null
    /* Seller country */
    var country: String? = null
    /* Inscription date (AAAA-MM-DDT00:00:00Z) */
    var inscriptionDate: java.util.Calendar? = null
    var social: UserSocial? = null
    var statistics: UserStatistics? = null
    var sellerRating: UserSellerRating? = null
    /* User right to report a product */
    var productReporter: Boolean? = null
    var badges: Array<UserBadge>? = null
    var apps: Array<UserApp>? = null
    /* VC's Internal Account */
    var internalAccount: Boolean? = null
    /* [Relationship] User's address */
    var address: Address? = null

    constructor(id: String, type: Type, firstname: String, civility: UserCivility, language: Language) : this() {
        this.id = id
        this.type = type
        this.firstname = firstname
        this.civility = civility
        this.language = language
    }


    enum class Type(val value: String) {
    
        user("user");
    
    }

}

