/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class UserCivility() {

    /* User civility name */
    lateinit var name: UserCivility.Name
    /* User civility name (localized) */
    lateinit var localizedName: UserCivility.LocalizedName    /* User gender ID (1 - Mr, 2 - Mrs, 3 - Miss) */
    var idGender: Int = 0


    constructor(name: Name, localizedName: LocalizedName, idGender: Int) : this() {
        this.name = name
        this.localizedName = localizedName
        this.idGender = idGender
    }


    enum class Name(val value: String) {
    
        mr("mr"),
    
        mrs("mrs"),
    
        miss("miss");
    
    }

    enum class LocalizedName(val value: String) {
    
        mr("mr"),
    
        mrs("mrs"),
    
        miss("miss"),
    
        mme("mme"),
    
        mlle("mlle"),
    
        sr.("sr."),
    
        sra.("sra."),
    
        srta.("srta."),
    
        sig.("sig."),
    
        sig.ra("sig.ra"),
    
        sig.na("sig.na"),
    
        herr("herr"),
    
        frau("frau"),
    
        fräulein("fräulein");
    
    }

}

