/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class UserSellerRating() {

    /* The seller badge */
    lateinit var badge: String
    var goals: UserSellerRatingGoals? = null
    var goalsThresholds: Array<UserGoalThreshold>? = null

    constructor(badge: String) : this() {
        this.badge = badge
    }


}

