/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class Warehouse() {

    /* Warehouse name */
    lateinit var name: String
    /* Localized warehouse name */
    lateinit var localizedName: String

    constructor(name: String, localizedName: String) : this() {
        this.name = name
        this.localizedName = localizedName
    }


}

