/**
* Atlas API Reference
*
* OpenAPI spec version: dev
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package fr.vestiairecollective.network.redesign.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
class WelcomeVoucher() {

    /* Voucher code */
    lateinit var voucherCode: String
    /* Min price for beeing eligible to discount */
    lateinit var threshold: Price
    /* Discount price */
    lateinit var discount: Price
    /* Voucher text */
    lateinit var text: String

    constructor(voucherCode: String, threshold: Price, discount: Price, text: String) : this() {
        this.voucherCode = voucherCode
        this.threshold = threshold
        this.discount = discount
        this.text = text
    }


}

